
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aayqonuflmkfgwtrsyke.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFheXFvbnVmbG1rZmd3dHJzeWtlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4NDA1NDMsImV4cCI6MjA1OTQxNjU0M30.pf6XONu5nP6y7rUTx_P12CNFw1Eh7xbJjyYA963INsI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
